config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'search_channels', to: 'channels#search_channels'
  resources :newsletters, only: [:index, :create, :show, :edit]
  resources :channels, only: [:show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link_parser.rb
class LinkParser
   
    def self.get_playlist_id(playlist_link)
        uri = URI.parse(playlist_link)
        args = CGI.parse(uri.query)
        args["list"].first
    end
    
end

app/models/newsletter_video.rb
class NewsletterVideo < ApplicationRecord
end

app/models/youtube_api_connector.rb
require 'net/http'

class YoutubeApiConnector
    API_KEY = ENV["GOOGLE_API_KEY"]
    OAUTH_CLIENT_ID = ENV["GOOGLE_CLIENT_ID"]
    OAUTH_CLIENT_SECRET = ENV["GOOGLE_CLIENT_SECRET"]
    
    def initialize()
        initialize_secret_keys()
    end
    
    def search_channels(search_str, max_results)
        url = "https://www.googleapis.com/youtube/v3/search?part=snippet&type=channel&q=#{URI::encode(search_str)}"
        items = get_resource_first_page(url, max_results)
        return items
    end
    
    def get_channels_infos(channels_ids)
        url = "https://www.googleapis.com/youtube/v3/channels?part=snippet%2CcontentDetails%2Cstatistics&id=#{channels_ids.join(",")}"
        items = get_resource_first_page(url, 10)
        return items
    end
    
    def get_channel_infos(channel_id)
        items = get_channels_infos([channel_id])
        return items.first
    end
    
    def get_channel_infos_by_username(username)
        url = "https://www.googleapis.com/youtube/v3/channels?part=snippet%2CcontentDetails%2Cstatistics&forUsername=#{username}"
        items = get_resource_first_page(url, 1)
        return items.first
    end
    
    def get_channel_uploaded_items(channel, max_results)
        playlist_id = channel["contentDetails"]["relatedPlaylists"]["uploads"]
        return get_playlist_items(playlist_id, max_results)
    end
    
    def get_playlist_items(playlist_id, max_results)
        url = "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet%2CcontentDetails&playlistId=#{playlist_id}"
        items = get_resource_first_page(url, max_results)
        return items
    end
    
    def get_videos_stats(playlist_items)
        videos_ids = playlist_items.map{ |playlist_item| playlist_item["contentDetails"]["videoId"] }.join(",")
        url = "https://www.googleapis.com/youtube/v3/videos?part=statistics&id=#{videos_ids}"
        items = get_resource_first_page(url, playlist_items.count)
        return items
    end
    
    def get_videos_infos(videos_ids)
        url = "https://www.googleapis.com/youtube/v3/videos?part=snippet&id=#{videos_ids.join(',')}"
        items = get_resource_first_page(url, videos_ids.count)
        return items
    end

    private
    
        def get_resource_all_pages(url)
            get_resource_page(url, nil)
        end
        
        def get_resource_first_page(url, max_results)
            full_url = URI.parse("#{url}&maxResults=#{max_results}&key=#{API_KEY}")
            res = Net::HTTP.get(full_url)
            json = ActiveSupport::JSON.decode(res)
            json["items"]
        end
        
        def get_resource_page(url, max_results, page_token)
            full_url = URI.parse("#{url}&maxResults=#{max_results}&key=#{API_KEY}&pageToken=#{page_token}")
            res = Net::HTTP.get(full_url)
            json = ActiveSupport::JSON.decode(res)
            items = json["items"]
            items = items + get_resource_page(url, json["nextPageToken"]) if json["nextPageToken"].present?
            
            return items
        end
    
        def initialize_secret_keys
            if(API_KEY.blank?)
                raise LoadError, "Can't find environment variable 'GOOGLE_API_KEY'"
            end
            
            if(OAUTH_CLIENT_ID.blank?)
                raise LoadError, "Can't find environment variable 'GOOGLE_CLIENT_ID'"
            end
            
            if(OAUTH_CLIENT_SECRET.blank?)
                raise LoadError, "Can't find environment variable 'GOOGLE_CLIENT_SECRET'"
            end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
    before_action :set_channel_id, only: [:show]
    
    def search_channels
        youtube_api = YoutubeApiConnector.new
        @search_input = channels_params["q"]
        if @search_input.present?
            @channels = youtube_api.search_channels(@search_input, 50)
        else
           @channels = [] 
        end
    end
    
    def show
        youtube_api = YoutubeApiConnector.new
        @channel = youtube_api.get_channel_infos(@channel_id)
        @playlist_items = youtube_api.get_channel_uploaded_items(@channel, 25)
        @videos_stats = youtube_api.get_videos_stats(@playlist_items)
        @last_views_count = @videos_stats.map{ |stats| Integer(stats["statistics"]["viewCount"] || 0) }.sum
        @last_likes_count = @videos_stats.map{ |stats| Integer(stats["statistics"]["likeCount"] || 0) }.sum
        @last_comms_count = @videos_stats.map{ |stats| Integer(stats["statistics"]["commentCount"] || 0) }.sum
    end
    
    private
    
        def set_channel_id
           @channel_id = params["id"] 
        end
    
        def channels_params
           params.permit("q")
        end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
   
    def index
       
    end
    
    def create
        @playlist_id = LinkParser.get_playlist_id(newsletter_params[:q])
        youtube_api = YoutubeApiConnector.new
        ap @playlist_id
        @playlist_items = youtube_api.get_playlist_items(@playlist_id, 10)
        videos_ids = @playlist_items.map{ |item| item["contentDetails"]["videoId"] }
        videos = youtube_api.get_videos_infos(videos_ids)
        channel_ids = videos.map{ |video| video["snippet"]["channelId"] }
        @channels = youtube_api.get_channels_infos(channel_ids)
        
        # Add channel infos to each video
        @playlist_items.each_with_index{ |item, index| item["channel"] = @channels[index] }
        
        @playlist_items.each{ |item|
            NewsletterVideo.create(
                playlist_id: @playlist_id,
                video_id: item["snippet"]["resourceId"]["videoId"],
                video_title: item["snippet"]["title"],
                video_thumbnail: item["snippet"]["thumbnails"]["medium"]["url"],
                channel_title: item["channel"]["snippet"]["title"],
                channel_desc: item["channel"]["snippet"]["description"],
                new_title: item["channel"]["snippet"]["title"] + " : " + item["snippet"]["title"],
                new_desc: item["channel"]["snippet"]["description"]
            ) unless NewsletterVideo.find_by(video_id: item["snippet"]["resourceId"]["videoId"])
        }
        redirect_to newsletter_path(@playlist_id)
    end
    
    def show
        @playlist_id = playlist_params[:id]
        @newsletter_videos = NewsletterVideo.where(playlist_id: @playlist_id)
    end
    
    def edit
        @playlist_id = playlist_params[:id]
        @newsletter_videos = NewsletterVideo.where(playlist_id: @playlist_id)
    end
    
    private
    
        def newsletter_params
           params.permit(:q) 
        end
        
        def playlist_params
           params.permit(:id) 
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def home
       
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/_overview.html.erb
<% channel ||= {} %>

<div class="card">
    <div class="row">
        <div class="col-xs-4 col-md-4">
            <%= image_tag channel["snippet"]["thumbnails"]["medium"]["url"], class: "img-fluid rounded" %>
        </div>
        <div class="col-xs-8 col-md-8">
            <strong><%= channel["snippet"]["title"] %></strong><br />
            <%= channel["snippet"]["description"] %>
        </div>
        <div class="col-md-12">
            <%= link_to "Stats", channel_path(channel["id"]["channelId"]), class: "btn btn-outline-success", style: "width: 100%;" %>
        </div>
    </div>
</div>

app/views/channels/_search_channels_bar.html.erb
<%= form_tag(search_channels_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
    <%= text_field_tag(:q, @search_input, class: "form-control mr-sm-2", placeholder: "Search a channel" ) %>
    <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0") %>
<% end %>

app/views/channels/search_channels.html.erb
<h1><%= @channels.count %> first channels for "<%= @search_input %>"</h1>

<div class="row">
    <% @channels.each do |channel| %>
        <div class="col-md-4 mb-3">
            <%= render partial: "channels/overview", locals: { channel: channel } %>
        </div>
    <% end %>    
</div>

app/views/channels/show.html.erb
<% channel = @channel %>
<% videos_stats = @videos_stats %>
<% last_views_count = @last_views_count %>
<% last_likes_count = @last_likes_count %>
<% last_comms_count = @last_comms_count %>


<div class="">
    <div class="row">
        <div class="col-xs-4 col-md-2 mb-3">
            <%= image_tag channel["snippet"]["thumbnails"]["medium"]["url"], class: "img-fluid rounded" %>
        </div>
        <div class="col-xs-8 col-md-10 mb-3">
            <h1><%= channel["snippet"]["title"] %></h1>
            <div class="mb-3">
                <%= channel["snippet"]["description"] %>
            </div>
            <div class="mb-3">
                <%= link_to "Youtube Channel", "https://youtube.com/channel/#{channel["id"]}", target: "blank", class: "btn btn-outline-danger" %>
            </div>
        </div>
        <div class="col-md-6 mb-3">
            <h2 class="h5">Global statistics :</h2>
            
            <% if !channel["statistics"]["hiddenSubscriberCount"] %>
                Subscribers : <%= number_with_delimiter(channel["statistics"]["subscriberCount"], delimiter: '.') %><br />
            <% end %>
            
            Videos : <%= number_with_delimiter(channel["statistics"]["videoCount"], delimiter: '.')%><br />
            
            Total Views : <%= number_with_delimiter(channel["statistics"]["viewCount"], delimiter: '.') %><br />
       
            Average Views/Video : <%= number_with_delimiter(Integer(channel["statistics"]["viewCount"]) / Integer(channel["statistics"]["videoCount"]), delimiter: '.') %><br />
        </div>
        <div class="col-md-6 mb-3">
            <h2 class="h5">On the last <%= videos_stats.count %> videos :</h2>
            
            Average Views/Video : <%= number_with_delimiter(last_views_count / videos_stats.count, delimiter: '.') %><br />
        
            Average Likes/Video : <%= number_with_delimiter(last_likes_count / videos_stats.count, delimiter: '.') %><br />
        
            Average Comments/Video : <%= number_with_delimiter(last_comms_count / videos_stats.count, delimiter: '.') %><br />
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Youdeo Internal Tool</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <%= link_to "Newsletter", newsletters_path, class: "nav-link" %>
          </li>
      </ul>
      
      <%= render partial: "channels/search_channels_bar" %>
      
    </div>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoudeoInternalTool</title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render partial: "layouts/navbar" %>
    <div class="container pt-3">
      <% if notice %><p class="notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert"><%= alert %></p><% end %>
      
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/newsletters/edit.html.erb
<div style="max-width: 564px">

    <% @newsletter_videos.each_with_index do |newsletter_video, index| %>
        <% video_id = newsletter_video.video_id %>
        <% video_title = newsletter_video.video_title %>
        <% video_thumbnail = newsletter_video.video_thumbnail %>
        <% channel_title = newsletter_video.channel_title %>
        <% channel_desc = newsletter_video.channel_desc %>
        

        <div>
            <%= image_tag video_thumbnail, class: "full_width" %>
        </div>
        <div>
            <%= label_tag :title, "Titre" %><br />
            <%= text_field_tag "title", channel_title + " : " + video_title, class: "full_width" %>
        </div>
        <div>
            <%= label_tag :description, "Description" %><br />
            <%= text_area_tag :description, channel_desc, class: "full_width" %>
        </div>
    <% end %>

</div>

app/views/newsletters/index.html.erb
<h1>Newsletter</h1>
<div class="subtitle">Let's craft !</div>

<%= form_tag newsletters_path do %>
  <%= text_field_tag(:q, "", placeholder: "Enter a playlist link") %>
  <%= submit_tag("Craft") %>
<% end %>

app/views/newsletters/show.html.erb
<% colors = ["#EBA91F", "#36BB93", "#E31565", "#7D43AE"] %>

<%= link_to "EDIT", edit_newsletter_path(@playlist_id), class: "btn btn-secondary" %>
<%= link_to "COPY", "", id: "copy_button", class: "btn btn-primary" %>
<%= text_field_tag "", "", id: "copy_temp" %>

<div id="copy_content" style="max-width: 564px">

    <% @newsletter_videos.each_with_index do |newsletter_video, index| %>
        <% video_id = newsletter_video.video_id %>
        <% video_title = newsletter_video.video_title %>
        <% video_thumbnail = newsletter_video.video_thumbnail %>
        <% channel_title = newsletter_video.channel_title %>
        <% channel_desc = newsletter_video.channel_desc %>
    
        <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageCardBlock" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
            <tbody class="mcnImageCardBlockOuter">
                <tr>
                    <td class="mcnImageCardBlockInner" valign="top" style="padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                        <table align="right" border="0" cellpadding="0" cellspacing="0" class="mcnImageCardBottomContent" width="100%" style="background-color: <%=colors[index]%>;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                            <tbody>
                                <tr>
                                    <td class="mcnImageCardBottomImageContent" align="center" valign="top" style="padding-top: 0px;padding-right: 0px;padding-bottom: 0;padding-left: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                        <a href="https://www.youtube.com/watch?v=<%= video_id %>&amp;list=<%= @playlist_id %>&amp;index=<%= index+1 %>" title="<%= channel_title %> : <%= video_title %>" class="" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">
                                            <img alt="<%= video_title %>" src="<%= video_thumbnail %>" width="564" style="max-width: 640px;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;vertical-align: bottom;" class="mcnImage">
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="mcnTextContent" valign="top" style="padding: 9px 18px;color: #F2F2F2;font-family: Helvetica;font-size: 14px;font-weight: normal;line-height: normal;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;" width="546">
                                        <div style="text-align: center;">
                                            <div style="text-align: center;"><strong><u><%= channel_title %> :</u> <em><%= video_title %></em></strong>
                                                <div style="text-align: justify;"><br>
                                                    <%= channel_desc %>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    <% end %>

</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-3">Hello, world!</h1>
  <p class="lead">You want stats ? Lots of stats ? Even more stats ?</p>
  <hr class="my-4">
  <p>Enter a channel name, and I will take care of everything</p>
  <p class="lead">
    <%= render partial: "channels/search_channels_bar" %>
  </p>
</div>